apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-gentle-world
spec:
  displayName: Gentle World
  author: 
    name: Gentle
    website: https://www.gentleworldcoming.com
  description: just a bit of fun
  logo: https://halo.run/logo
  website: https://github.com/halo-dev/theme-modern-starter
  repo: https://github.com/Gentle-Huang/theme-gentle-world.git
  settingName: "theme-gentle-world-setting"
  configMapName: "theme-gentle-world-configMap"
  version: 1.0.0
  require: 2.0.0
